import{useEffect,useRef,useState}from'react';import{api}from'../services/api';import{socket}from'../services/socket';
type Device={_id:string;deviceName:string;cameraIndex:number;status:string;battery?:number;socketId?:string};type Session={_id:string;sessionName:string;pairingCode:string;status:string};
const format=(s:number)=>new Date(s*1000).toISOString().slice(11,19);
export function Director(){
 const [session,setSession]=useState<Session|null>(null),[devices,setDevices]=useState<Device[]>([]),[qr,setQr]=useState(''),[active,setActive]=useState(1),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[stream,setStream]=useState<MediaStream|null>(null); const program=useRef<HTMLVideoElement>(null);
 useEffect(()=>{if(program.current&&stream)program.current.srcObject=stream},[stream]);useEffect(()=>{if(!recording)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[recording]);
 useEffect(()=>{socket.connect();socket.on('device:paired',(d:Device)=>setDevices(x=>[...x.filter(v=>v._id!==d._id),d]));socket.on('device:heartbeat',(d:Device)=>setDevices(x=>x.map(v=>v._id===d._id?d:v)));
 socket.on('webrtc:offer',async ({from,sdp})=>{try {const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.ontrack=e=>setStream(e.streams[0]);pc.onicecandidate=e=>{if(e.candidate)socket.emit('webrtc:ice-candidate',{to:from,candidate:e.candidate})};await pc.setRemoteDescription(sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('webrtc:answer',{to:from,sdp:pc.localDescription});}catch{setError('WebRTC connection failed. Check Wi-Fi and browser permissions.')}});return()=>{socket.disconnect();socket.off()};},[]);
 async function create(){try{const payload={sessionName:'Podcast '+new Date().toLocaleDateString()};const r=await api('/api/sessions',{method:'POST',body:JSON.stringify(payload)});setSession(r.session);setQr(r.qr);socket.emit('director:join',{sessionId:r.session._id})}catch(e){setError((e as Error).message)}} async function record(action:'start'|'stop'|'pause'){if(!session)return;try{await api('/api/sessions/'+session._id+'/recording/'+action,{method:'POST'});setRecording(action==='start');if(action==='start')setSeconds(0)}catch(e){setError((e as Error).message)}}
 return <main className="studio"><header><div><span className="eyebrow">CREATOR: DEVESH KUMAR CHAUHAN</span><h1>DEVESH PODCAST STUDIO</h1><p>Professional Multi-Camera Podcast Studio</p></div><div className="ready">● SYSTEM READY<br/><small>WebRTC · MediaRecorder · WebSocket</small></div></header>{!session?<section className="empty"><h2>Ready to direct?</h2><p>Create a private studio session, then pair up to three phones.</p><button onClick={create}>CREATE NEW SESSION</button>{error&&<p className="error">{error}</p>}</section>:<><section className="pair"><div><span className="eyebrow">PAIRING CODE · EXPIRES IN 10 MINUTES</span><strong>{session.pairingCode}</strong><p>Open <code>/mobile</code> on each phone and enter this code.</p></div><img src={qr} alt="Pairing QR code"/><div><b>{devices.length}/3 CAMERAS CONNECTED</b><p>{session.sessionName}</p></div></section><section className="grid">{[1,2,3].map(i=>{const d=devices.find(x=>x.cameraIndex===i);return <article className={'camera '+(active===i?'selected':'')} onClick={()=>setActive(i)} key={i}><div className="feed">{active===i&&stream?<video ref={program} autoPlay playsInline muted/>:<span>CAMERA {i}<small>{d?'LIVE FEED ON PROGRAM':'AWAITING DEVICE'}</small></span>}</div><h3>{d?.deviceName||['HOST CAMERA','GUEST CAMERA','WIDE CAMERA'][i-1]}</h3><p className={d?.status==='connected'?'good':''}>● {d?.status?.toUpperCase()||'OFFLINE'}</p><small>{d?`Camera ${i} · Battery ${d.battery??'—'}% · Wi-Fi monitoring active`:'Pair a phone to this position'}</small></article>})}</section><section className="program"><div><span className="eyebrow">PROGRAM VIEW · CAM {active}</span><div className="program-video">{stream?<video ref={program} autoPlay playsInline muted/>:'SELECTED CAMERA PREVIEW'}</div></div><aside><div className="timer">{format(seconds)}</div><p className={recording?'rec':''}>{recording?'● RECORDING':'● STANDBY'}</p><div className="buttons">{[1,2,3].map(i=><button className="outline" onClick={()=>setActive(i)} key={i}>CAM {i}</button>)}</div><button disabled={recording} onClick={()=>record('start')}>START RECORDING</button><button className="danger" disabled={!recording} onClick={()=>record('stop')}>STOP RECORDING</button><button className="outline" onClick={()=>record('pause')}>PAUSE</button></aside></section>{error&&<p className="error">{error}</p>}</>}</main>}
