import{useEffect,useRef,useState}from'react';import{api}from'../services/api';import{socket}from'../services/socket';

const validSessionId=(value:string)=>/^[a-f\d]{24}$/i.test(value.trim());
const validPairingCode=(value:string)=>/^\d{6}$/.test(value.trim());

export function Mobile(){const params=new URLSearchParams(location.search);const[sessionId,setSessionId]=useState(params.get('session')?.trim()||''),[code,setCode]=useState(params.get('code')?.trim()||''),[name,setName]=useState('Phone Camera'),[status,setStatus]=useState('NOT CONNECTED'),[error,setError]=useState(''),[device,setDevice]=useState<any>(null),[recording,setRecording]=useState(false);const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream>(),recorder=useRef<MediaRecorder>();
async function start(){setError('');const secureContext=location.protocol==='https:'||location.hostname==='localhost';if(!secureContext){setError('Camera access requires HTTPS. Open the secure app URL or use localhost.');return}try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is unavailable in this browser.');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:true});stream.current=s;if(video.current)video.current.srcObject=s;setStatus('CAMERA READY');if(device)connect(s)}catch(e){const reason=e as DOMException;setError(reason.name==='NotAllowedError'?'Camera or microphone permission denied. Allow access in your browser settings and try again.':reason.name==='SecurityError'?'Camera access was blocked because this page is not using HTTPS.':'Camera unavailable. '+reason.message)}}
async function pair(){setError('');const id=sessionId.trim(),pairingCode=code.trim();if(!validSessionId(id)){setError('Enter a valid 24-character session ID.');return}if(!validPairingCode(pairingCode)){setError('Enter the 6-digit pairing code from the director.');return}try{const r=await api(`/api/sessions/${encodeURIComponent(id)}/pair`,{method:'POST',body:JSON.stringify({code:pairingCode,deviceName:name.trim()})});setDevice(r.device);localStorage.setItem('device_token',r.deviceToken);setStatus('PAIRED — START CAMERA');setError('')}catch(e){setError((e as Error).message)}}
function connect(s:MediaStream){socket.connect();socket.emit('device:join',{sessionId,deviceToken:localStorage.getItem('device_token')});socket.on('device:ready',async({device:ready,iceServers})=>{setDevice(ready);setStatus('CONNECTED ✓');const pc=new RTCPeerConnection({iceServers});s.getTracks().forEach(t=>pc.addTrack(t,s));pc.onicecandidate=e=>e.candidate&&socket.emit('webrtc:ice-candidate',{to:undefined,candidate:e.candidate});const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('webrtc:offer',{sdp:pc.localDescription})});socket.on('recording:start',()=>beginRecording());socket.on('recording:stop',()=>endRecording())}
function beginRecording(){if(!stream.current||recording)return;try{const rec=new MediaRecorder(stream.current,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'}),chunks:Blob[]=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`camera-${device?.cameraIndex||'01'}.webm`;a.click();setRecording(false)};rec.start(1000);recorder.current=rec;setRecording(true)}catch{setError('Recording could not start. This browser may not support MediaRecorder.')}}
function endRecording(){recorder.current?.state==='recording'&&recorder.current.stop()}function stop(){stream.current?.getTracks().forEach(t=>t.stop());setStatus('CAMERA STOPPED');socket.disconnect()}async function switchCamera(){stop();await start()}useEffect(()=>()=>stop(),[]);
return <main className="mobile"><header><span className="eyebrow">DEVESH PODCAST STUDIO</span><h1>CAMERA DEVICE</h1></header>{!device?<section className="pair-form"><input placeholder="Session ID" value={sessionId} onChange={e=>setSessionId(e.target.value)}/><input placeholder="6-digit pairing code" value={code} onChange={e=>setCode(e.target.value)}/><input placeholder="Device name" value={name} onChange={e=>setName(e.target.value)}/><button onClick={pair}>PAIR THIS CAMERA</button></section>:<><video className="mobile-preview" ref={video} autoPlay playsInline muted/><div className="status"><b>{status}</b><span>{recording?'● RECORDING':'Microphone: Available'}</span><span>Device: {device.deviceName}</span><span>Network: Wi-Fi required</span></div><div className="mobile-buttons"><button onClick={start}>START CAMERA</button><button className="outline" onClick={stop}>STOP CAMERA</button><button className="outline" onClick={switchCamera}>SWITCH CAMERA</button></div></>}{error&&<p className="error">{error}</p>}<small className="limit">Bluetooth pairing is handled by your phone’s system settings. Camera access needs HTTPS when not on localhost.</small></main>}
